// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/chenyl99x/toge-api/internal/app"
	"github.com/chenyl99x/toge-api/internal/handler"
	"github.com/chenyl99x/toge-api/internal/repository"
	"github.com/chenyl99x/toge-api/internal/service"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp() (*app.App, error) {
	engine := ProvideGinEngine()
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	authHandler := handler.NewAuthHandler(userService)
	healthHandler := handler.NewHealthHandler()
	userHandler := handler.NewUserHandler(userService)
	timezoneHandler := handler.NewTimezoneHandler()
	appApp := app.NewApp(engine, authHandler, healthHandler, userHandler, timezoneHandler)
	return appApp, nil
}
