// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"git.lulumia.fun/root/toge-api/internal/app"
	"git.lulumia.fun/root/toge-api/internal/handler"
	"git.lulumia.fun/root/toge-api/internal/repository"
	"git.lulumia.fun/root/toge-api/internal/service"
)

// Injectors from wire.go:

// InitializeApp 初始化应用
func InitializeApp() (*app.App, error) {
	engine := ProvideGinEngine()
	userRepository := repository.NewUserRepository()
	userService := service.NewUserService(userRepository)
	authHandler := handler.NewAuthHandler(userService)
	healthHandler := handler.NewHealthHandler()
	userHandler := handler.NewUserHandler(userService)
	timezoneHandler := handler.NewTimezoneHandler()
	personRepository := repository.NewPersonRepository()
	personService := service.NewPersonService(personRepository)
	personHandler := handler.NewPersonHandler(personService)
	nationRepository := repository.NewNationRepository()
	nationService := service.NewNationService(nationRepository)
	nationHandler := handler.NewNationHandler(nationService)
	versionRepository := repository.NewVersionRepository()
	versionService := service.NewVersionService(versionRepository)
	versionHandler := handler.NewVersionHandler(versionService)
	artifactSetRepository := repository.NewArtifactSetRepository()
	artifactSetService := service.NewArtifactSetService(artifactSetRepository)
	artifactSetHandler := handler.NewArtifactSetHandler(artifactSetService)
	artifactRepository := repository.NewArtifactRepository()
	artifactService := service.NewArtifactService(artifactRepository)
	artifactHandler := handler.NewArtifactHandler(artifactService)
	appApp := app.NewApp(engine, authHandler, healthHandler, userHandler, timezoneHandler, personHandler, nationHandler, versionHandler, artifactSetHandler, artifactHandler)
	return appApp, nil
}
